# Generated by Django 2.2.24 on 2022-05-30 10:38

from django.db import migrations


def fill_new_buiding_field(apps, schema_editor):
    new_buiding_sign = 2015
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= new_buiding_sign
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_buiding_field),
    ]
