# Generated by Django 2.2.24 on 2022-05-30 13:28

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    country_code = 'RU'
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_number = phonenumbers.parse(
            flat.owners_phonenumber,
            country_code,
            )
        if phonenumbers.is_valid_number(parsed_phone_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_phone_number,
                phonenumbers.PhoneNumberFormat.E164,
                )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220530_1621'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
