# Generated by Django 2.2.24 on 2022-05-30 14:23

from django.db import migrations


def import_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        owner_obj, _ = Owner.objects.get_or_create(
            name=flat.owner_deprecated,
            phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
            )
        owner_obj.flats.add(flat)
        owner_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220530_1718'),
    ]

    operations = [
        migrations.RunPython(import_owners_data),
    ]
