# Generated by Django 2.2.24 on 2022-05-30 15:59

from django.db import migrations


def import_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat_owners = Owner.objects.filter(flats=flat)
        for owner in flat_owners:
            flat.owners.add(owner)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220530_1845'),
    ]

    operations = [
        migrations.RunPython(import_owners_to_flats),
    ]
