# Generated by Django 2.2.24 on 2022-05-30 15:59

from django.db import migrations


def import_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        owner_obj, _ = Owner.objects.get_or_create(
            name=flat.owner_deprecated,
            phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
            )
        owner_obj.save()
        flat.owners.add(owner_obj)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220530_1845'),
    ]

    operations = [
        migrations.RunPython(import_owners_to_flats),
    ]
