# Generated by Django 2.2.24 on 2022-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20220608_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(related_name='flat_owners', to='property.Owner', verbose_name='Собственники'),
        ),
    ]
